# Site settings
title: Adam Fraser
email: adamfraser0@gmail.com
description: "Portfolio Site for Adam Fraser"
baseurl: ""
url: "http://adamfraser.com"

# Build settings
markdown: kramdown
permalink: pretty
